parameters:
  max_steps: 1000
  total_bandwidth: 100
  aver_req_min: 0.5
  aver_req_max: 1.0
  users_min: 10
  users_max: 100
  requirement_interval_min: 40
  requirement_interval_max: 80
  lambda_throughput_embb: 1.0
  lambda_delay_embb: -0.5
  lambda_violation_embb: -0.5
  lambda_throughput_urllc: 0.5
  lambda_delay_urllc: -1.0
  lambda_violation_urllc: -0.5
